name: Build and Publish Installer

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
  CT_SUBDOMAIN: ${{ vars.CT_SUBDOMAIN }}
  GH_TOKEN_TO_CHECK_RELEASES: ${{ secrets.GH_TOKEN }}
  PUBLISHER_EMAIL: ${{ vars.PUBLISHER_EMAIL }}
  PUBLISHER_NAME: ${{ vars.PUBLISHER_NAME }}
  PUBLISHER_URL: ${{ vars.PUBLISHER_URL }}
  RELEASE_TAG: ${{ github.event.release.tag_name || 'v0.0.0' }}
  RELEASES_URL: https://api.github.com/repos/${{ github.repository }}/releases
  YT_STREAM_URL: ${{ vars.YT_STREAM_URL }}

jobs:
  build-installer:
    environment: installer
    runs-on: windows-latest

    steps:
      - name: Print env vars
        shell: pwsh
        run: |
          Write-Host "Env vars set:"
          Get-ChildItem Env:

      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create installer script from template
        shell: pwsh
        run: |
          $template = Get-Content installer/installer.template.ps1 -Raw -Encoding UTF8
          $script = $template -replace '__RELEASES_URL__', $env:RELEASES_URL `
                              -replace '__RELEASE_TAG__', $env:RELEASE_TAG `
                              -replace '__CT_SUBDOMAIN__', $env:CT_SUBDOMAIN `
                              -replace '__GH_TOKEN__', $env:GH_TOKEN_TO_CHECK_RELEASES `
                              -replace '__YT_STREAM_URL__', $env:YT_STREAM_URL
          $script | Set-Content installer/installer.ps1 -Encoding UTF8

      - name: Copy GitHub.psm1 module to installer
        shell: pwsh
        run: |
          $destinationPath = "installer"
          $sourcePath = "cli_code/Modules/GitHub.psm1"
      
          if (Test-Path $sourcePath) {
            Copy-Item -Path $sourcePath -Destination $destinationPath -Force
            Write-Host "MeinModul.psm1 wurde erfolgreich nach '$destinationPath' kopiert."
          } else {
            Write-Error "Die Datei 'MeinModul.psm1' wurde nicht gefunden: $sourcePath"
          }

      - name: Create Inno Setup script from template
        working-directory: installer
        shell: pwsh
        run: |
          $template = Get-Content bgh-cli.template.iss -Encoding UTF8
          $iss = $template -replace '__RELEASE_TAG__', $env:RELEASE_TAG `
                              -replace '__PUBLISHER_NAME__', $env:PUBLISHER_NAME `
                              -replace '__PUBLISHER_URL__', $env:PUBLISHER_URL `
                              -replace '__PUBLISHER_EMAIL__', $env:PUBLISHER_EMAIL
          $iss | Set-Content bgh-cli.iss -Encoding UTF8

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile installer with Inno Setup
        working-directory: installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" bgh-cli.iss

      - name: Upload installer to current release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: installer/bgh-cli-installer.exe
          asset_name: bgh-cli-installer.exe
          asset_content_type: application/octet-stream