name: Build and Publish Installer

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  ZIP_URL: ${{ vars.ZIP_URL }}
  RELEASE_TAG: ${{ github.event.release.tag_name || 'v0.0.0' }}

jobs:
  build-installer:
    environment: installer
    runs-on: windows-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create installer script from template
        shell: pwsh
        run: |
          $template = Get-Content installer/installer.template.ps1 -Encoding UTF8
          $script = $template -replace '__ZIP_URL__', $env:ZIP_URL -replace '__RELEASE_TAG__', $env:RELEASE_TAG
          $script | Set-Content installer/installer.ps1 -Encoding UTF8

      - name: Create Inno Setup script from template
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          $template = Get-Content installer/ct-cli.template.iss -Encoding UTF8
          $iconPath = Join-Path $PWD "installer\icon.ico"
          $iss = $template -replace '__RELEASE_TAG__', $env:RELEASE_TAG -replace '__ICON_PATH__', $iconPath.Replace('\', '\\')
          $iss | Set-Content installer/ct-cli.iss -Encoding UTF8

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile installer with Inno Setup
        working-directory: ${{ github.workspace }}
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer/ct-cli.iss

      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: Annika-Klu/ct-cli-files
          token: ${{ secrets.CT_CLI_FILES_TOKEN }}
          path: public-repo
          fetch-depth: 0

      - name: Copy Inno Setup installer to public repo
        run: |
          if (!(Test-Path "public-repo/installer")) {
            New-Item -ItemType Directory -Path "public-repo/installer" -Force
          }
          Copy-Item "installer/ct-cli-installer.exe" "public-repo/installer/ct-cli-installer.exe" -Force

      - name: Commit & Push to public repo (branch installer)
        working-directory: public-repo
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add installer/ct-cli-installer.exe
          if (git diff-index --quiet HEAD) {
            Write-Host "No changes to commit"
          } else {
            git commit -m "Update Inno Setup installer"
            git push origin master