name: Build and Publish Installer

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
  UPDATE_URL: https://github.com/${{ github.repository }}releases/latest/download/ct-cli.zip
  PUBLISHER_NAME: ${{ vars.PUBLISHER_NAME }}
  PUBLISHER_URL: ${{ vars.PUBLISHER_URL }}
  PUBLISHER_EMAIL: ${{ vars.PUBLISHER_EMAIL }}
  CT_SUBDOMAIN: ${{ vars.CT_SUBDOMAIN }}
  RELEASE_TAG: ${{ github.event.release.tag_name || 'v0.0.0' }}

jobs:
  build-installer:
    environment: installer
    runs-on: windows-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create installer script from template
        shell: pwsh
        run: |
          $template = Get-Content installer/installer.template.ps1 -Raw -Encoding UTF8
          $script = $template -replace '__UPDATE_URL__', $env:UPDATE_URL `
                              -replace '__RELEASE_TAG__', $env:RELEASE_TAG `
                              -replace '__CT_SUBDOMAIN__', $env:CT_SUBDOMAIN
          $script | Set-Content installer/installer.ps1 -Encoding UTF8NoBOM

      - name: Create Inno Setup script from template
        working-directory: installer
        shell: pwsh
        run: |
          $template = Get-Content ct-cli.template.iss -Encoding UTF8
          $iss = $template -replace '__RELEASE_TAG__', $env:RELEASE_TAG `
                              -replace '__PUBLISHER_NAME__', $env:PUBLISHER_NAME `
                              -replace '__PUBLISHER_URL__', $env:PUBLISHER_URL `
                              -replace '__PUBLISHER_EMAIL__', $env:PUBLISHER_EMAIL
          $iss | Set-Content ct-cli.iss -Encoding UTF8

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile installer with Inno Setup
        working-directory: installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ct-cli.iss

      - name: Upload installer to current release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: installer/ct-cli-installer.exe
          asset_name: ct-cli-installer.exe
          asset_content_type: application/octet-stream