name: Post Release Info to CLI Group

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CT_LOGIN_TOKEN: ${{ secrets.CT_LOGIN_TOKEN }}
  CT_API_URL: "https://${{ vars.CT_SUBDOMAIN }}.church.tools/api"
  CT_GROUP_ID: ${{ secrets.CT_GROUP_ID }}

jobs:
  get-and-post-release-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get Release Information
        run: |
          echo "Will post"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release body: ${{ github.event.release.body }}"

          RELEASE_TAG="${{ github.event.release.tag_name }}"
          TITLE="Neue Version $RELEASE_TAG"
          RELEASE_BODY="${{ github.event.release.body }}"

          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV
      
      - name: Post Release Information to Group via API
        run: |
          curl -X POST "$CT_API_URL/posts" \
          -H "Authorization: Login $CT_LOGIN_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "groupId": "${{ secrets.CT_GROUP_ID }}",
            "title": "$TITLE",
            "content": "$RELEASE_BODY",
            "visibility": "group_intern"
          }'